# Use the official gcc image
image: ubuntu:18.04

before_script:
    # Install build dependencies
    - apt -y update
    - apt -y install build-essential
    - apt -y install make
    - apt -y install zlib1g-dev
    - apt -y install libpng-dev
    - apt -y install libjpeg62-dev
    - apt -y install libgif-dev
    - apt -y install libncurses5-dev
    - apt -y install libfreetype6-dev
    - apt -y install libx11-dev
    - apt -y install libxrender-dev
    - apt -y install libgl1-mesa-dev
    - apt -y install libxext-dev
    - apt -y install upx-ucl
    - apt -y install libsqlite3-dev
    - apt -y install libssl-dev
    - apt -y install libffi-dev
    - apt -y install libasound2-dev
    - apt -y install libcurl4-openssl-dev
    - apt -y install libfontconfig1-dev

ecere-sdk:
    # Build the application
    stage: build
    script:
        - make troubleshoot
        - make print-all-vars-stat
        - make
    artifacts:
        paths:
        - obj/
        expire_in: 1 week
