version: 18
jobs:
- name: Build
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Build
    runInContainer: true
    image: ubuntu:18.04
    interpreter: !DefaultInterpreter
      commands:
      - apt -y update
      - apt -y install build-essential
      - apt -y install make
      - apt -y install zlib1g-dev
      - apt -y install libpng-dev
      - apt -y install libjpeg62-dev
      - apt -y install libgif-dev
      - apt -y install libncurses5-dev
      - apt -y install libfreetype6-dev
      - apt -y install libx11-dev
      - apt -y install libxrender-dev
      - apt -y install libgl1-mesa-dev
      - apt -y install libxext-dev
      - apt -y install upx-ucl
      - apt -y install libsqlite3-dev
      - apt -y install libssl-dev
      - apt -y install libffi-dev
      - apt -y install libasound2-dev
      - apt -y install libcurl4-openssl-dev
      - apt -y install libfontconfig1-dev
#       make bindings CXXFLAGS="-std=c++1z -fno-exceptions -fno-rtti" -j2 &&
      - make -j2 &&
        mkdir output &&
        make install DESTDIR=output &&
        cd output &&
        tar czf @project_name@-@tag@-@branch@-@commit_hash@-@build_number@-output-linux-x86_64.tar.gz * &&
        cd .. &&
        tar czf @project_name@-@tag@-@branch@-@commit_hash@-@build_number@-deps-linux-x86_64.tar.gz deps &&
        tar czf @project_name@-@tag@-@branch@-@commit_hash@-@build_number@-extras-butterbur-src.tar.gz extras butterbur/src compiler/eccss ecere/src ide/src/designer/SyntaxHighlighting.ec ide/src/designer/SyntaxColorScheme.ec ide/res/actions default.cf crossplatform.mk &&
        cd obj &&
        tar czf @project_name@-@tag@-@branch@-@commit_hash@-@build_number@-binaries-linux-x86_64.tar.gz *
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: ArtefactsBinaries
    sourcePath: output
    artifacts: '@project_name@-@tag@-@branch@-@commit_hash@-@build_number@-output-linux-x86_64.tar.gz'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: ArtefactsBinaries
    sourcePath: obj
    artifacts: '@project_name@-@tag@-@branch@-@commit_hash@-@build_number@-binaries-linux-x86_64.tar.gz'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: ArtefactsDeps
    sourcePath: .
    artifacts: '@project_name@-@tag@-@branch@-@commit_hash@-@build_number@-deps-linux-x86_64.tar.gz'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: ArtefactsExtrasButterburSource
    sourcePath: .
    artifacts: '@project_name@-@tag@-@branch@-@commit_hash@-@build_number@-extras-butterbur-src.tar.gz'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !PullRequestUpdateTrigger
    projects: ecere-sdk
  - !BranchUpdateTrigger
    projects: ecere-sdk
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
