version: 20
jobs:
- name: Build
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Build
    runInContainer: true
    image: ubuntu:18.04
    interpreter: !DefaultInterpreter
      commands:
      - rm /etc/apt/apt.conf.d/docker-clean
      - echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/98keep-debs
      - echo 'APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/99keep-debs
      - dpkg --add-architecture i386
      - apt -y update
      - apt -y install build-essential
      - apt -y install gcc-8
      - apt -y install g++-8
      - apt -y install gcc-multilib
      - apt -y install mingw-w64
      - apt -y install make
      - apt -y install upx-ucl
      - apt -y install zlib1g-dev
      - apt -y install libpng-dev
      - apt -y install libjpeg62-dev
      - apt -y install libgif-dev
      - apt -y install libncurses5-dev
      - apt -y install libfreetype6-dev
      - apt -y install libx11-dev
      - apt -y install libxrender-dev
      - apt -y install libgl1-mesa-dev
      - apt -y install libxext-dev
      - apt -y install libsqlite3-dev
      - apt -y install libssl-dev
      - apt -y install libffi-dev
      - apt -y install libasound2-dev
      - apt -y install libcurl4-openssl-dev
      - apt -y install libfontconfig1-dev
      - apt -y install zlib1g-dev:i386
      - apt -y install libpng-dev:i386
      - apt -y install libjpeg62-dev:i386
      - apt -y install libncurses5-dev:i386
      - apt -y install libfreetype6-dev:i386
      - apt -y install libx11-dev:i386
      - apt -y install libxrender-dev:i386
      - apt -y install libgl1-mesa-dev:i386
      - apt -y install libxext-dev:i386
      - apt -y install libsqlite3-dev:i386
      - apt -y install libssl-dev:i386
      - apt -y install libffi-dev:i386
      - apt -y install libasound2-dev:i386
      - apt -y install libcurl4-openssl-dev:i386
      - apt -y install libfontconfig1-dev:i386
      - apt -y install wget
      - apt -y install git
      - apt -y install python3-pip
      - pip3 install cffi
      - make -j2 && mkdir output && make install DESTDIR=output && rm /usr/bin/gcc
        && rm /usr/bin/g++ && ln -s /usr/bin/gcc-8 /usr/bin/gcc && ln -s /usr/bin/g++-8
        /usr/bin/g++ && make bindings && rm /usr/bin/gcc && rm /usr/bin/g++ && ln
        -s /usr/bin/gcc-7 /usr/bin/gcc && ln -s /usr/bin/g++-7 /usr/bin/g++ && apt
        -y install libgif-dev:i386 && make ARCH=x32 -j2 && make ARCH=x32 install DESTDIR=output
        && tar czf @project_name@-@tag@-@branch@-@commit_hash@-@build_number@-extras-butterbur-src.tar.gz
        extras butterbur/src compiler/eccss ecere/src ide/src/designer/SyntaxHighlighting.ec
        ide/src/designer/SyntaxColorScheme.ec ide/res/actions default.cf crossplatform.mk
        && cd output && tar czf @project_name@-@tag@-@branch@-@commit_hash@-@build_number@-output-linux.tar.gz
        * && cd .. && cd obj && tar czf @project_name@-@tag@-@branch@-@commit_hash@-@build_number@-binaries-linux-x86_64.tar.gz
        linux && tar czf @project_name@-@tag@-@branch@-@commit_hash@-@build_number@-binaries-linux-i686.tar.gz
        linux.x32 && cd .. && tar czf @project_name@-@tag@-@branch@-@commit_hash@-@build_number@-bindings-linux-x86_64.tar.gz
        bindings && wget https://ecere.com/tmp/win32-patches.tar.gz && tar xf win32-patches.tar.gz
        && ln -s $(pwd)/win32/regex/regex.h /usr/x86_64-w64-mingw32/include/ && ln
        -s $(pwd)/win32/regex/gnurx-0.dll /usr/x86_64-w64-mingw32/lib/ && ln -s $(pwd)/win32/regex/regex.h
        /usr/i686-w64-mingw32/include/ && ln -s $(pwd)/win32/regex-x32/libgnurx-0.dll
        /usr/i686-w64-mingw32/lib/ && apt -y install libgif-dev && make PLATFORM=win32
        OPENSSL_CONF=$(pwd)/win32/openssl/bin/openssl.cfg && mkdir output-win32 &&
        make PLATFORM=win32 OPENSSL_CONF=$(pwd)/win32/openssl/bin/openssl.cfg DESTDIR=output-win32
        install && cd output-win32 && tar czf @project_name@-@tag@-@branch@-@commit_hash@-@build_number@-output-windows-x86_64.tar.gz
        * && cd .. && apt -y install libgif-dev:i386 && make PLATFORM=win32 ARCH=x32
        OPENSSL_CONF=$(pwd)/win32/openssl-x32/bin/openssl.cfg && mkdir output-win32-x32
        && make PLATFORM=win32 ARCH=x32 OPENSSL_CONF=$(pwd)/win32/openssl-x32/bin/openssl.cfg
        DESTDIR=output-win32-x32 install && cd output-win32-x32 && tar czf @project_name@-@tag@-@branch@-@commit_hash@-@build_number@-output-windows-i686.tar.gz
        * && cd .. && make PLATFORM=win32 ARCH=x32 OPENSSL_CONF=$(pwd)/win32/openssl-x32/bin/openssl.cfg
        installer && tar czf @project_name@-@tag@-@branch@-@commit_hash@-@build_number@-deps.tar.gz
        deps && cd obj && tar czf @project_name@-@tag@-@branch@-@commit_hash@-@build_number@-binaries-windows-x86_64.tar.gz
        win32 && tar czf @project_name@-@tag@-@branch@-@commit_hash@-@build_number@-binaries-windows-i686.tar.gz
        win32.x32 && cd .. && cp installer/obj/release.win32.x32/setup-ecere-0.44.16pre-win32.exe
        @project_name@-@tag@-@branch@-@commit_hash@-@build_number@-setup-ecere-0.44.16pre-win32.exe
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: ArtefactsLinuxInstall
    sourcePath: output
    artifacts: '@project_name@-@tag@-@branch@-@commit_hash@-@build_number@-output-linux.tar.gz'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: ArtefactsWindowsInstall
    sourcePath: output-win32
    artifacts: '@project_name@-@tag@-@branch@-@commit_hash@-@build_number@-output-windows-x86_64.tar.gz'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: ArtefactsWindows32BitInstall
    sourcePath: output-win32-x32
    artifacts: '@project_name@-@tag@-@branch@-@commit_hash@-@build_number@-output-windows-i686.tar.gz'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: ArtefactsLinuxBinaries
    sourcePath: obj
    artifacts: '@project_name@-@tag@-@branch@-@commit_hash@-@build_number@-binaries-linux-x86_64.tar.gz'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: ArtefactsLinux32BitBinaries
    sourcePath: obj
    artifacts: '@project_name@-@tag@-@branch@-@commit_hash@-@build_number@-binaries-linux-i686.tar.gz'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: ArtefactsLinuxBindings
    sourcePath: .
    artifacts: '@project_name@-@tag@-@branch@-@commit_hash@-@build_number@-bindings-linux-x86_64.tar.gz'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: ArtefactsWindowsBinaries
    sourcePath: obj
    artifacts: '@project_name@-@tag@-@branch@-@commit_hash@-@build_number@-binaries-windows-x86_64.tar.gz'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: ArtefactsWindows32BitBinaries
    sourcePath: obj
    artifacts: '@project_name@-@tag@-@branch@-@commit_hash@-@build_number@-binaries-windows-i686.tar.gz'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: ArtefactsDeps
    sourcePath: .
    artifacts: '@project_name@-@tag@-@branch@-@commit_hash@-@build_number@-deps.tar.gz'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: ArtefactsExtrasButterburSource
    sourcePath: .
    artifacts: '@project_name@-@tag@-@branch@-@commit_hash@-@build_number@-extras-butterbur-src.tar.gz'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: WindowsInstaller
    sourcePath: .
    artifacts: '@project_name@-@tag@-@branch@-@commit_hash@-@build_number@-setup-ecere-0.44.16pre-win32.exe'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !PullRequestUpdateTrigger
    projects: ecere-sdk
  - !BranchUpdateTrigger
    projects: ecere-sdk
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  caches:
  - key: AptCache
    path: /var/cache/apt
  - key: AptList
    path: /var/lib/apt/lists
  - key: pip
    path: /root/.cache/pip
  timeout: 3600
