.TH DOCUMENTOR "1" "August 2012" "documentor" "Ecere SDK/API Reference Tool"
.SH NAME
documentor \- Ecere API Reference Tool
.SH SYNOPSIS
.IX
documentor [\fIec-shared-library-name-or-path\fR] | [\fIec-symbol-file\fR (\fB.sym\fR)]
.SH DESCRIPTION
Brings up the Ecere API Reference Tool.

Modules (eC shared library or symbol file) whose API you want to browse and/or contribute to can be specified on the command line.

If no name is specified, the libecere API will show up by default.

Changes will be saved in the documentation path specified in the application's File/Settings menu (Defaults to /usr/share/ecere/doc), with the file name: \fImodule-name\fR\fB.eCdoc\fR. 