.TH ECERE-IDE "1" "August 2016" "ecere-ide" "Ecere SDK/Integrated Development Environment"
.SH NAME
ecere-ide \- Ecere IDE
.SH SYNOPSIS
.IX
ecere-ide [\fIproject\fR] [\fIfiles\fR]*
.SH DESCRIPTION
Launches the Ecere Integrated Environment.

A \fIproject\fR (\fB.epj\fR) and/or \fIfiles\fR to be opened on startup can be specified on the command line.

.SH SETTINGS
Settings for the IDE are stored in ~/.ecereIDE/
